name: 'olist_analytics'
version: '1.0.0'
config-version: 2

profile: 'olist_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  olist_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +materialized: table
      analytics:
        +materialized: table

seeds:
  olist_analytics:
    +schema: raw
    +quote_columns: false

vars:
  current_date: "{{ modules.datetime.datetime.now().strftime('%Y-%m-%d') }}"
